!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_ensdam_storfg_gen_field_2s_new (ranfield, lon,&
     & lat, pow_spect, lmin, lmax, f2py_ranfield_d0)
      use ensdam_storfg, only : gen_field_2s_new
                use ensdam_storfg, only: fun_pow_spect_sph
      procedure(fun_pow_spect_sph) :: pow_spect
      integer lmin
      integer lmax
      integer f2py_ranfield_d0
      real(kind=8) ranfield(f2py_ranfield_d0)
      real(kind=8) lon(size(ranfield,1))
      real(kind=8) lat(size(ranfield,1))
      call gen_field_2s_new(ranfield, lon, lat, pow_spect, lmin, lmax)
      end subroutine f2pywrap_ensdam_storfg_gen_field_2s_new
      subroutine f2pywrap_ensdam_storfg_gen_field_2s_new2 (ranfield, lon&
     &, lat, pow_spect, lmin, lmax, f2py_ranfield_d0, f2py_ranfield_d1)
      use ensdam_storfg, only : gen_field_2s_new2
                use ensdam_storfg, only: fun_pow_spect_sph
      procedure(fun_pow_spect_sph) :: pow_spect
      integer lmin
      integer lmax
      integer f2py_ranfield_d0
      integer f2py_ranfield_d1
      real(kind=8) ranfield(f2py_ranfield_d0,f2py_ranfield_d1)
      real(kind=8) lon(size(ranfield,1),size(ranfield,2))
      real(kind=8) lat(size(ranfield,1),size(ranfield,2))
      call gen_field_2s_new2(ranfield, lon, lat, pow_spect, lmin, lmax)
      end subroutine f2pywrap_ensdam_storfg_gen_field_2s_new2
      
      subroutine f2pyinitensdam_storfg(f2pysetupfunc)
      use ensdam_storfg, only : storfg_ylm_resolution
      interface 
      subroutine f2pywrap_ensdam_storfg_gen_field_2s_new (ranfield, lon,&
     & lat, pow_spect, lmin, lmax, f2py_ranfield_d0)
      external pow_spect
      integer lmin
      integer lmax
      integer f2py_ranfield_d0
      real(kind=8) ranfield(f2py_ranfield_d0)
      real(kind=8) lon(size(ranfield,1))
      real(kind=8) lat(size(ranfield,1))
      end subroutine f2pywrap_ensdam_storfg_gen_field_2s_new 
      subroutine f2pywrap_ensdam_storfg_gen_field_2s_new2 (ranfield, lon&
     &, lat, pow_spect, lmin, lmax, f2py_ranfield_d0, f2py_ranfield_d1)
      external pow_spect
      integer lmin
      integer lmax
      integer f2py_ranfield_d0
      integer f2py_ranfield_d1
      real(kind=8) ranfield(f2py_ranfield_d0,f2py_ranfield_d1)
      real(kind=8) lon(size(ranfield,1),size(ranfield,2))
      real(kind=8) lat(size(ranfield,1),size(ranfield,2))
      end subroutine f2pywrap_ensdam_storfg_gen_field_2s_new2
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(storfg_ylm_resolution,f2pywrap_ensdam_storfg_ge&
     &n_field_2s_new,f2pywrap_ensdam_storfg_gen_field_2s_new2)
      end subroutine f2pyinitensdam_storfg


