!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_ensdam_anaobs_ana_obs (anaobs, obsens, obs, ob&
     &serror, quadef, quaref, f2py_anaobs_d0, f2py_anaobs_d1, f2py_obsen&
     &s_d1, f2py_quadef_d0)
      use ensdam_anaobs, only : ana_obs
      integer f2py_anaobs_d0
      integer f2py_anaobs_d1
      integer f2py_obsens_d1
      integer f2py_quadef_d0
      real(kind=8) anaobs(f2py_anaobs_d0,f2py_anaobs_d1)
      real(kind=8) obsens(size(anaobs,1),f2py_obsens_d1)
      real(kind=8) obs(size(anaobs,1))
      real(kind=8) obserror(size(anaobs,1))
      real(kind=8) quadef(f2py_quadef_d0)
      real(kind=8) quaref(size(quadef,1))
      call ana_obs(anaobs, obsens, obs, obserror, quadef, quaref)
      end subroutine f2pywrap_ensdam_anaobs_ana_obs
      subroutine f2pywrap_ensdam_anaobs_ana_obs_sym (anaobs, obs, obserr&
     &or, obsqua, quaref, f2py_anaobs_d0, f2py_anaobs_d1, f2py_obsqua_d1&
     &)
      use ensdam_anaobs, only : ana_obs_sym
      integer f2py_anaobs_d0
      integer f2py_anaobs_d1
      integer f2py_obsqua_d1
      real(kind=8) anaobs(f2py_anaobs_d0,f2py_anaobs_d1)
      real(kind=8) obs(size(anaobs,1))
      real(kind=8) obserror(size(anaobs,1))
      real(kind=8) obsqua(size(anaobs,1),f2py_obsqua_d1)
      real(kind=8) quaref(size(obsqua,2))
      call ana_obs_sym(anaobs, obs, obserror, obsqua, quaref)
      end subroutine f2pywrap_ensdam_anaobs_ana_obs_sym
      
      subroutine f2pyinitensdam_anaobs(f2pysetupfunc)
      interface 
      subroutine f2pywrap_ensdam_anaobs_ana_obs (anaobs, obsens, obs, ob&
     &serror, quadef, quaref, f2py_anaobs_d0, f2py_anaobs_d1, f2py_obsen&
     &s_d1, f2py_quadef_d0)
      integer f2py_anaobs_d0
      integer f2py_anaobs_d1
      integer f2py_obsens_d1
      integer f2py_quadef_d0
      real(kind=8) anaobs(f2py_anaobs_d0,f2py_anaobs_d1)
      real(kind=8) obsens(size(anaobs,1),f2py_obsens_d1)
      real(kind=8) obs(size(anaobs,1))
      real(kind=8) obserror(size(anaobs,1))
      real(kind=8) quadef(f2py_quadef_d0)
      real(kind=8) quaref(size(quadef,1))
      end subroutine f2pywrap_ensdam_anaobs_ana_obs 
      subroutine f2pywrap_ensdam_anaobs_ana_obs_sym (anaobs, obs, obserr&
     &or, obsqua, quaref, f2py_anaobs_d0, f2py_anaobs_d1, f2py_obsqua_d1&
     &)
      integer f2py_anaobs_d0
      integer f2py_anaobs_d1
      integer f2py_obsqua_d1
      real(kind=8) anaobs(f2py_anaobs_d0,f2py_anaobs_d1)
      real(kind=8) obs(size(anaobs,1))
      real(kind=8) obserror(size(anaobs,1))
      real(kind=8) obsqua(size(anaobs,1),f2py_obsqua_d1)
      real(kind=8) quaref(size(obsqua,2))
      end subroutine f2pywrap_ensdam_anaobs_ana_obs_sym
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_anaobs_ana_obs,f2pywrap_ensdam_&
     &anaobs_ana_obs_sym)
      end subroutine f2pyinitensdam_anaobs

      subroutine f2pywrap_ensdam_anaqua_ens_quantiles_vector (qua, ens, &
     &quadef, enswei, ensweiloc, f2py_qua_d0, f2py_qua_d1, f2py_ens_d1)
      use ensdam_anaqua, only : ens_quantiles_vector
      integer f2py_qua_d0
      integer f2py_qua_d1
      integer f2py_ens_d1
      real(kind=8) qua(f2py_qua_d0,f2py_qua_d1)
      real(kind=8) ens(size(qua,1),f2py_ens_d1)
      real(kind=8) quadef(size(qua,2))
      real(kind=8) enswei(size(ens,2))
      real(kind=8) ensweiloc(size(qua,1),size(ens,2))
      call ens_quantiles_vector(qua, ens, quadef, enswei, ensweiloc)
      end subroutine f2pywrap_ensdam_anaqua_ens_quantiles_vector
      subroutine f2pywrap_ensdam_anaqua_ens_quantiles_variable (qua, ens&
     &, quadef, enswei, f2py_qua_d0, f2py_ens_d0)
      use ensdam_anaqua, only : ens_quantiles_variable
      integer f2py_qua_d0
      integer f2py_ens_d0
      real(kind=8) qua(f2py_qua_d0)
      real(kind=8) ens(f2py_ens_d0)
      real(kind=8) quadef(size(qua,1))
      real(kind=8) enswei(size(ens,1))
      call ens_quantiles_variable(qua, ens, quadef, enswei)
      end subroutine f2pywrap_ensdam_anaqua_ens_quantiles_variable
      
      subroutine f2pyinitensdam_anaqua(f2pysetupfunc)
      use ensdam_anaqua, only : heapsort
      use ensdam_anaqua, only : heapsort2
      interface 
      subroutine f2pywrap_ensdam_anaqua_ens_quantiles_vector (qua, ens, &
     &quadef, enswei, ensweiloc, f2py_qua_d0, f2py_qua_d1, f2py_ens_d1)
      integer f2py_qua_d0
      integer f2py_qua_d1
      integer f2py_ens_d1
      real(kind=8) qua(f2py_qua_d0,f2py_qua_d1)
      real(kind=8) ens(size(qua,1),f2py_ens_d1)
      real(kind=8) quadef(size(qua,2))
      real(kind=8) enswei(size(ens,2))
      real(kind=8) ensweiloc(size(qua,1),size(ens,2))
      end subroutine f2pywrap_ensdam_anaqua_ens_quantiles_vector 
      subroutine f2pywrap_ensdam_anaqua_ens_quantiles_variable (qua, ens&
     &, quadef, enswei, f2py_qua_d0, f2py_ens_d0)
      integer f2py_qua_d0
      integer f2py_ens_d0
      real(kind=8) qua(f2py_qua_d0)
      real(kind=8) ens(f2py_ens_d0)
      real(kind=8) quadef(size(qua,1))
      real(kind=8) enswei(size(ens,1))
      end subroutine f2pywrap_ensdam_anaqua_ens_quantiles_variable
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_anaqua_ens_quantiles_vector,f2p&
     &ywrap_ensdam_anaqua_ens_quantiles_variable,heapsort,heapsort2)
      end subroutine f2pyinitensdam_anaqua

      subroutine f2pywrap_ensdam_anatra_ana_forward_ensemble (ens, qua, &
     &quaref, rank_bn, f2py_ens_d0, f2py_ens_d1, f2py_qua_d1, f2py_rank_&
     &bn_d0)
      use ensdam_anatra, only : ana_forward_ensemble
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_qua_d1
      integer f2py_rank_bn_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) qua(size(ens,1),f2py_qua_d1)
      real(kind=8) quaref(size(qua,2))
      real(kind=8) rank_bn(f2py_rank_bn_d0)
      call ana_forward_ensemble(ens, qua, quaref, rank_bn)
      end subroutine f2pywrap_ensdam_anatra_ana_forward_ensemble
      subroutine f2pywrap_ensdam_anatra_ana_forward_vector (vct, qua, qu&
     &aref, rank_bn, f2py_vct_d0, f2py_qua_d1)
      use ensdam_anatra, only : ana_forward_vector
      real(kind=8) rank_bn
      integer f2py_vct_d0
      integer f2py_qua_d1
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) qua(size(vct,1),f2py_qua_d1)
      real(kind=8) quaref(size(qua,2))
      call ana_forward_vector(vct, qua, quaref, rank_bn)
      end subroutine f2pywrap_ensdam_anatra_ana_forward_vector
      subroutine f2pywrap_ensdam_anatra_ana_forward_variable (var, qua, &
     &quaref, rank_bn, f2py_qua_d0)
      use ensdam_anatra, only : ana_forward_variable
      real(kind=8) var
      real(kind=8) rank_bn
      integer f2py_qua_d0
      real(kind=8) qua(f2py_qua_d0)
      real(kind=8) quaref(size(qua,1))
      call ana_forward_variable(var, qua, quaref, rank_bn)
      end subroutine f2pywrap_ensdam_anatra_ana_forward_variable
      subroutine f2pywrap_ensdam_anatra_ana_backward_ensemble (ens, qua,&
     & quaref, f2py_ens_d0, f2py_ens_d1, f2py_qua_d1)
      use ensdam_anatra, only : ana_backward_ensemble
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_qua_d1
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) qua(size(ens,1),f2py_qua_d1)
      real(kind=8) quaref(size(qua,2))
      call ana_backward_ensemble(ens, qua, quaref)
      end subroutine f2pywrap_ensdam_anatra_ana_backward_ensemble
      subroutine f2pywrap_ensdam_anatra_ana_backward_vector (vct, qua, q&
     &uaref, f2py_vct_d0, f2py_qua_d1)
      use ensdam_anatra, only : ana_backward_vector
      integer f2py_vct_d0
      integer f2py_qua_d1
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) qua(size(vct,1),f2py_qua_d1)
      real(kind=8) quaref(size(qua,2))
      call ana_backward_vector(vct, qua, quaref)
      end subroutine f2pywrap_ensdam_anatra_ana_backward_vector
      subroutine f2pywrap_ensdam_anatra_ana_backward_variable (var, qua,&
     & quaref, f2py_qua_d0)
      use ensdam_anatra, only : ana_backward_variable
      real(kind=8) var
      integer f2py_qua_d0
      real(kind=8) qua(f2py_qua_d0)
      real(kind=8) quaref(size(qua,1))
      call ana_backward_variable(var, qua, quaref)
      end subroutine f2pywrap_ensdam_anatra_ana_backward_variable
      
      subroutine f2pyinitensdam_anatra(f2pysetupfunc)
      interface 
      subroutine f2pywrap_ensdam_anatra_ana_forward_ensemble (ens, qua, &
     &quaref, rank_bn, f2py_ens_d0, f2py_ens_d1, f2py_qua_d1, f2py_rank_&
     &bn_d0)
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_qua_d1
      integer f2py_rank_bn_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) qua(size(ens,1),f2py_qua_d1)
      real(kind=8) quaref(size(qua,2))
      real(kind=8) rank_bn(f2py_rank_bn_d0)
      end subroutine f2pywrap_ensdam_anatra_ana_forward_ensemble 
      subroutine f2pywrap_ensdam_anatra_ana_forward_vector (vct, qua, qu&
     &aref, rank_bn, f2py_vct_d0, f2py_qua_d1)
      real(kind=8) rank_bn
      integer f2py_vct_d0
      integer f2py_qua_d1
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) qua(size(vct,1),f2py_qua_d1)
      real(kind=8) quaref(size(qua,2))
      end subroutine f2pywrap_ensdam_anatra_ana_forward_vector 
      subroutine f2pywrap_ensdam_anatra_ana_forward_variable (var, qua, &
     &quaref, rank_bn, f2py_qua_d0)
      real(kind=8) var
      real(kind=8) rank_bn
      integer f2py_qua_d0
      real(kind=8) qua(f2py_qua_d0)
      real(kind=8) quaref(size(qua,1))
      end subroutine f2pywrap_ensdam_anatra_ana_forward_variable 
      subroutine f2pywrap_ensdam_anatra_ana_backward_ensemble (ens, qua,&
     & quaref, f2py_ens_d0, f2py_ens_d1, f2py_qua_d1)
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_qua_d1
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) qua(size(ens,1),f2py_qua_d1)
      real(kind=8) quaref(size(qua,2))
      end subroutine f2pywrap_ensdam_anatra_ana_backward_ensemble 
      subroutine f2pywrap_ensdam_anatra_ana_backward_vector (vct, qua, q&
     &uaref, f2py_vct_d0, f2py_qua_d1)
      integer f2py_vct_d0
      integer f2py_qua_d1
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) qua(size(vct,1),f2py_qua_d1)
      real(kind=8) quaref(size(qua,2))
      end subroutine f2pywrap_ensdam_anatra_ana_backward_vector 
      subroutine f2pywrap_ensdam_anatra_ana_backward_variable (var, qua,&
     & quaref, f2py_qua_d0)
      real(kind=8) var
      integer f2py_qua_d0
      real(kind=8) qua(f2py_qua_d0)
      real(kind=8) quaref(size(qua,1))
      end subroutine f2pywrap_ensdam_anatra_ana_backward_variable
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_anatra_ana_forward_ensemble,f2p&
     &ywrap_ensdam_anatra_ana_forward_vector,f2pywrap_ensdam_anatra_ana_&
     &forward_variable,f2pywrap_ensdam_anatra_ana_backward_ensemble,f2py&
     &wrap_ensdam_anatra_ana_backward_vector,f2pywrap_ensdam_anatra_ana_&
     &backward_variable)
      end subroutine f2pyinitensdam_anatra

      subroutine f2pywrap_ensdam_anautil_ana_util_quaref (quaref, quadef&
     &, f2py_quaref_d0)
      use ensdam_anautil, only : ana_util_quaref
      integer f2py_quaref_d0
      real(kind=8) quaref(f2py_quaref_d0)
      real(kind=8) quadef(size(quaref,1))
      call ana_util_quaref(quaref, quadef)
      end subroutine f2pywrap_ensdam_anautil_ana_util_quaref
      
      subroutine f2pyinitensdam_anautil(f2pysetupfunc)
      use ensdam_anautil, only : a
      use ensdam_anautil, only : reference_cdf
      use ensdam_anautil, only : b
      use ensdam_anautil, only : ana_util_init
      interface 
      subroutine f2pywrap_ensdam_anautil_ana_util_quaref (quaref, quadef&
     &, f2py_quaref_d0)
      integer f2py_quaref_d0
      real(kind=8) quaref(f2py_quaref_d0)
      real(kind=8) quadef(size(quaref,1))
      end subroutine f2pywrap_ensdam_anautil_ana_util_quaref
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(a,reference_cdf,b,ana_util_init,f2pywrap_ensdam&
     &_anautil_ana_util_quaref)
      end subroutine f2pyinitensdam_anautil

      subroutine f2pywrap_ensdam_covariance_ensemble_correlation (ens, e&
     &nsref, correl, weight, f2py_ens_d0, f2py_ens_d1, f2py_weight_d0)
      use ensdam_covariance, only : ensemble_correlation
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_weight_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) ensref(size(ens,2))
      real(kind=8) correl(size(ens,1))
      real(kind=8) weight(f2py_weight_d0)
      call ensemble_correlation(ens, ensref, correl, weight)
      end subroutine f2pywrap_ensdam_covariance_ensemble_correlation
      subroutine f2pywrap_ensdam_covariance_ensemble_representer (ens, e&
     &nsref, representer, weight, f2py_ens_d0, f2py_ens_d1, f2py_weight_&
     &d0)
      use ensdam_covariance, only : ensemble_representer
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_weight_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) ensref(size(ens,2))
      real(kind=8) representer(size(ens,1))
      real(kind=8) weight(f2py_weight_d0)
      call ensemble_representer(ens, ensref, representer, weight)
      end subroutine f2pywrap_ensdam_covariance_ensemble_representer
      subroutine f2pywrap_ensdam_covariance_ensemble_covariance (ens, en&
     &sref, cov, weight, f2py_ens_d0, f2py_ens_d1, f2py_weight_d0)
      use ensdam_covariance, only : ensemble_covariance
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_weight_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) ensref(size(ens,2))
      real(kind=8) cov(size(ens,1))
      real(kind=8) weight(f2py_weight_d0)
      call ensemble_covariance(ens, ensref, cov, weight)
      end subroutine f2pywrap_ensdam_covariance_ensemble_covariance
      subroutine f2pywrap_ensdam_covariance_update_meancov_vector (vct, &
     &varref, memidx, mean, meanref, mproda, f2py_vct_d0)
      use ensdam_covariance, only : update_meancov_vector
      real(kind=8) varref
      integer memidx
      real(kind=8) meanref
      integer f2py_vct_d0
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) mean(size(vct,1))
      real(kind=8) mproda(size(vct,1))
      call update_meancov_vector(vct, varref, memidx, mean, meanref, mpr&
     &oda)
      end subroutine f2pywrap_ensdam_covariance_update_meancov_vector
      subroutine f2pywrap_ensdam_covariance_update_meancov_vector_weight&
     & (vct, varref, weight, weightsum, mean, meanref, mproda, f2py_vct_&
     &d0)
      use ensdam_covariance, only : update_meancov_vector_weight
      real(kind=8) varref
      real(kind=8) weight
      real(kind=8) weightsum
      real(kind=8) meanref
      integer f2py_vct_d0
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) mean(size(vct,1))
      real(kind=8) mproda(size(vct,1))
      call update_meancov_vector_weight(vct, varref, weight, weightsum, &
     &mean, meanref, mproda)
      end subroutine f2pywrap_ensdam_covariance_update_meancov_vector_we&
     &ight
      
      subroutine f2pyinitensdam_covariance(f2pysetupfunc)
      use ensdam_covariance, only : update_meancov_variable
      use ensdam_covariance, only : update_meancov_variable_weight
      interface 
      subroutine f2pywrap_ensdam_covariance_ensemble_correlation (ens, e&
     &nsref, correl, weight, f2py_ens_d0, f2py_ens_d1, f2py_weight_d0)
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_weight_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) ensref(size(ens,2))
      real(kind=8) correl(size(ens,1))
      real(kind=8) weight(f2py_weight_d0)
      end subroutine f2pywrap_ensdam_covariance_ensemble_correlation 
      subroutine f2pywrap_ensdam_covariance_ensemble_representer (ens, e&
     &nsref, representer, weight, f2py_ens_d0, f2py_ens_d1, f2py_weight_&
     &d0)
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_weight_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) ensref(size(ens,2))
      real(kind=8) representer(size(ens,1))
      real(kind=8) weight(f2py_weight_d0)
      end subroutine f2pywrap_ensdam_covariance_ensemble_representer 
      subroutine f2pywrap_ensdam_covariance_ensemble_covariance (ens, en&
     &sref, cov, weight, f2py_ens_d0, f2py_ens_d1, f2py_weight_d0)
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_weight_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) ensref(size(ens,2))
      real(kind=8) cov(size(ens,1))
      real(kind=8) weight(f2py_weight_d0)
      end subroutine f2pywrap_ensdam_covariance_ensemble_covariance 
      subroutine f2pywrap_ensdam_covariance_update_meancov_vector (vct, &
     &varref, memidx, mean, meanref, mproda, f2py_vct_d0)
      real(kind=8) varref
      integer memidx
      real(kind=8) meanref
      integer f2py_vct_d0
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) mean(size(vct,1))
      real(kind=8) mproda(size(vct,1))
      end subroutine f2pywrap_ensdam_covariance_update_meancov_vector 
      subroutine f2pywrap_ensdam_covariance_update_meancov_vector_weight&
     & (vct, varref, weight, weightsum, mean, meanref, mproda, f2py_vct_&
     &d0)
      real(kind=8) varref
      real(kind=8) weight
      real(kind=8) weightsum
      real(kind=8) meanref
      integer f2py_vct_d0
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) mean(size(vct,1))
      real(kind=8) mproda(size(vct,1))
      end subroutine f2pywrap_ensdam_covariance_update_meancov_vector_we&
     &ight
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_covariance_ensemble_correlation&
     &,f2pywrap_ensdam_covariance_ensemble_representer,f2pywrap_ensdam_c&
     &ovariance_ensemble_covariance,f2pywrap_ensdam_covariance_update_me&
     &ancov_vector,f2pywrap_ensdam_covariance_update_meancov_vector_weig&
     &ht,update_meancov_variable,update_meancov_variable_weight)
      end subroutine f2pyinitensdam_covariance

      subroutine f2pywrap_ensdam_ensaugm_sample_augmented_ensemble (maxc&
     &hain, augens, ens, multiplicity, f2py_augens_d0, f2py_augens_d1, f&
     &2py_ens_d1, f2py_ens_d2, f2py_multiplicity_d0)
      use ensdam_ensaugm, only : sample_augmented_ensemble
      integer maxchain
      integer f2py_augens_d0
      integer f2py_augens_d1
      integer f2py_ens_d1
      integer f2py_ens_d2
      integer f2py_multiplicity_d0
      real(kind=8) augens(f2py_augens_d0,f2py_augens_d1)
      real(kind=8) ens(size(augens,1),f2py_ens_d1,f2py_ens_d2)
      integer multiplicity(f2py_multiplicity_d0)
      call sample_augmented_ensemble(maxchain, augens, ens, multiplicity&
     &)
      end subroutine f2pywrap_ensdam_ensaugm_sample_augmented_ensemble
      subroutine f2pywrap_ensdam_ensaugm_newproduct (new_bn, ens, multip&
     &licity, sample, f2py_new_bn_d0, f2py_ens_d1, f2py_ens_d2, f2py_mul&
     &tiplicity_d0, f2py_sample_d0)
      use ensdam_ensaugm, only : newproduct
      integer f2py_new_bn_d0
      integer f2py_ens_d1
      integer f2py_ens_d2
      integer f2py_multiplicity_d0
      integer f2py_sample_d0
      real(kind=8) new_bn(f2py_new_bn_d0)
      real(kind=8) ens(size(new_bn,1),f2py_ens_d1,f2py_ens_d2)
      integer multiplicity(f2py_multiplicity_d0)
      integer sample(f2py_sample_d0)
      call newproduct(new_bn, ens, multiplicity, sample)
      end subroutine f2pywrap_ensdam_ensaugm_newproduct
      subroutine f2pywrap_ensdam_ensaugm_getproduct (new_bn, ens, multip&
     &licity, sample, f2py_new_bn_d0, f2py_ens_d1, f2py_ens_d2, f2py_mul&
     &tiplicity_d0, f2py_sample_d0)
      use ensdam_ensaugm, only : getproduct
      integer f2py_new_bn_d0
      integer f2py_ens_d1
      integer f2py_ens_d2
      integer f2py_multiplicity_d0
      integer f2py_sample_d0
      real(kind=8) new_bn(f2py_new_bn_d0)
      real(kind=8) ens(size(new_bn,1),f2py_ens_d1,f2py_ens_d2)
      integer multiplicity(f2py_multiplicity_d0)
      integer sample(f2py_sample_d0)
      call getproduct(new_bn, ens, multiplicity, sample)
      end subroutine f2pywrap_ensdam_ensaugm_getproduct
      
      subroutine f2pyinitensdam_ensaugm(f2pysetupfunc)
      use ensdam_ensaugm, only : ensaugm_chain_index
      use ensdam_ensaugm, only : mpi_comm_ensaugm
      use ensdam_ensaugm, only : ensaugm_with_renormalization
      interface 
      subroutine f2pywrap_ensdam_ensaugm_sample_augmented_ensemble (maxc&
     &hain, augens, ens, multiplicity, f2py_augens_d0, f2py_augens_d1, f&
     &2py_ens_d1, f2py_ens_d2, f2py_multiplicity_d0)
      integer maxchain
      integer f2py_augens_d0
      integer f2py_augens_d1
      integer f2py_ens_d1
      integer f2py_ens_d2
      integer f2py_multiplicity_d0
      real(kind=8) augens(f2py_augens_d0,f2py_augens_d1)
      real(kind=8) ens(size(augens,1),f2py_ens_d1,f2py_ens_d2)
      integer multiplicity(f2py_multiplicity_d0)
      end subroutine f2pywrap_ensdam_ensaugm_sample_augmented_ensemble 
      subroutine f2pywrap_ensdam_ensaugm_newproduct (new_bn, ens, multip&
     &licity, sample, f2py_new_bn_d0, f2py_ens_d1, f2py_ens_d2, f2py_mul&
     &tiplicity_d0, f2py_sample_d0)
      integer f2py_new_bn_d0
      integer f2py_ens_d1
      integer f2py_ens_d2
      integer f2py_multiplicity_d0
      integer f2py_sample_d0
      real(kind=8) new_bn(f2py_new_bn_d0)
      real(kind=8) ens(size(new_bn,1),f2py_ens_d1,f2py_ens_d2)
      integer multiplicity(f2py_multiplicity_d0)
      integer sample(f2py_sample_d0)
      end subroutine f2pywrap_ensdam_ensaugm_newproduct 
      subroutine f2pywrap_ensdam_ensaugm_getproduct (new_bn, ens, multip&
     &licity, sample, f2py_new_bn_d0, f2py_ens_d1, f2py_ens_d2, f2py_mul&
     &tiplicity_d0, f2py_sample_d0)
      integer f2py_new_bn_d0
      integer f2py_ens_d1
      integer f2py_ens_d2
      integer f2py_multiplicity_d0
      integer f2py_sample_d0
      real(kind=8) new_bn(f2py_new_bn_d0)
      real(kind=8) ens(size(new_bn,1),f2py_ens_d1,f2py_ens_d2)
      integer multiplicity(f2py_multiplicity_d0)
      integer sample(f2py_sample_d0)
      end subroutine f2pywrap_ensdam_ensaugm_getproduct
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(ensaugm_chain_index,mpi_comm_ensaugm,ensaugm_wi&
     &th_renormalization,f2pywrap_ensdam_ensaugm_sample_augmented_ensemb&
     &le,f2pywrap_ensdam_ensaugm_newproduct,f2pywrap_ensdam_ensaugm_getp&
     &roduct)
      end subroutine f2pyinitensdam_ensaugm

      subroutine f2pywrap_ensdam_interp_grid2d_init (kxg, kyg, gtype, f2&
     &py_kxg_d0, f2py_kxg_d1)
      use ensdam_interp, only : grid2d_init
      integer f2py_kxg_d0
      integer f2py_kxg_d1
      real(kind=8) kxg(f2py_kxg_d0,f2py_kxg_d1)
      real(kind=8) kyg(size(kxg,1),size(kxg,2))
      character(len=*) gtype
      call grid2d_init(kxg, kyg, gtype)
      end subroutine f2pywrap_ensdam_interp_grid2d_init
      subroutine f2pywrap_ensdam_interp_grid1d_locate (grid1d_locatef2py&
     &wrap, kgrid, kx, ki, f2py_kgrid_d0)
      use ensdam_interp, only : grid1d_locate
      real(kind=8) kx
      integer ki
      integer f2py_kgrid_d0
      real(kind=8) kgrid(f2py_kgrid_d0)
      logical grid1d_locatef2pywrap
      grid1d_locatef2pywrap = .not.(.not.grid1d_locate(kgrid, kx, ki))
      end subroutine f2pywrap_ensdam_interp_grid1d_locate
      subroutine f2pywrap_ensdam_interp_grid2d_locate (grid2d_locatef2py&
     &wrap, kx, ky, ki, kj)
      use ensdam_interp, only : grid2d_locate
      real(kind=8) kx
      real(kind=8) ky
      integer ki
      integer kj
      logical grid2d_locatef2pywrap
      grid2d_locatef2pywrap = .not.(.not.grid2d_locate(kx, ky, ki, kj))
      end subroutine f2pywrap_ensdam_interp_grid2d_locate
      subroutine f2pywrap_ensdam_interp_grid1d_interp (kgrid, kx, ki, w,&
     & f2py_kgrid_d0)
      use ensdam_interp, only : grid1d_interp
      real(kind=8) kx
      integer ki
      real(kind=8) w
      integer f2py_kgrid_d0
      real(kind=8) kgrid(f2py_kgrid_d0)
      call grid1d_interp(kgrid, kx, ki, w)
      end subroutine f2pywrap_ensdam_interp_grid1d_interp
      
      subroutine f2pyinitensdam_interp(f2pysetupfunc)
      use ensdam_interp, only : grid2d_interp
      interface 
      subroutine f2pywrap_ensdam_interp_grid2d_init (kxg, kyg, gtype, f2&
     &py_kxg_d0, f2py_kxg_d1)
      integer f2py_kxg_d0
      integer f2py_kxg_d1
      real(kind=8) kxg(f2py_kxg_d0,f2py_kxg_d1)
      real(kind=8) kyg(size(kxg,1),size(kxg,2))
      character(len=*) gtype
      end subroutine f2pywrap_ensdam_interp_grid2d_init 
      subroutine f2pywrap_ensdam_interp_grid1d_locate (grid1d_locatef2py&
     &wrap, grid1d_locate, kgrid, kx, ki, f2py_kgrid_d0)
      logical grid1d_locate
      real(kind=8) kx
      integer ki
      integer f2py_kgrid_d0
      real(kind=8) kgrid(f2py_kgrid_d0)
      logical grid1d_locatef2pywrap
      end subroutine f2pywrap_ensdam_interp_grid1d_locate 
      subroutine f2pywrap_ensdam_interp_grid2d_locate (grid2d_locatef2py&
     &wrap, grid2d_locate, kx, ky, ki, kj)
      logical grid2d_locate
      real(kind=8) kx
      real(kind=8) ky
      integer ki
      integer kj
      logical grid2d_locatef2pywrap
      end subroutine f2pywrap_ensdam_interp_grid2d_locate 
      subroutine f2pywrap_ensdam_interp_grid1d_interp (kgrid, kx, ki, w,&
     & f2py_kgrid_d0)
      real(kind=8) kx
      integer ki
      real(kind=8) w
      integer f2py_kgrid_d0
      real(kind=8) kgrid(f2py_kgrid_d0)
      end subroutine f2pywrap_ensdam_interp_grid1d_interp
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_interp_grid2d_init,f2pywrap_ens&
     &dam_interp_grid1d_locate,f2pywrap_ensdam_interp_grid2d_locate,f2py&
     &wrap_ensdam_interp_grid1d_interp,grid2d_interp)
      end subroutine f2pyinitensdam_interp

      subroutine f2pywrap_ensdam_meanstd_ensemble_meanstd_vector (ens, m&
     &ean, std, weight, f2py_ens_d0, f2py_ens_d1)
      use ensdam_meanstd, only : ensemble_meanstd_vector
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) mean(size(ens,1))
      real(kind=8) std(size(ens,1))
      real(kind=8) weight(size(ens,1),size(ens,2))
      call ensemble_meanstd_vector(ens, mean, std, weight)
      end subroutine f2pywrap_ensdam_meanstd_ensemble_meanstd_vector
      subroutine f2pywrap_ensdam_meanstd_ensemble_meanstd_variable (ens,&
     & mean, std, weight, f2py_ens_d0, f2py_weight_d0)
      use ensdam_meanstd, only : ensemble_meanstd_variable
      real(kind=8) mean
      real(kind=8) std
      integer f2py_ens_d0
      integer f2py_weight_d0
      real(kind=8) ens(f2py_ens_d0)
      real(kind=8) weight(f2py_weight_d0)
      call ensemble_meanstd_variable(ens, mean, std, weight)
      end subroutine f2pywrap_ensdam_meanstd_ensemble_meanstd_variable
      subroutine f2pywrap_ensdam_meanstd_update_meanstd_vector (vct, idx&
     &, mean, msqra, f2py_vct_d0, f2py_mean_d0, f2py_msqra_d0)
      use ensdam_meanstd, only : update_meanstd_vector
      integer idx
      integer f2py_vct_d0
      integer f2py_mean_d0
      integer f2py_msqra_d0
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) mean(f2py_mean_d0)
      real(kind=8) msqra(f2py_msqra_d0)
      call update_meanstd_vector(vct, idx, mean, msqra)
      end subroutine f2pywrap_ensdam_meanstd_update_meanstd_vector
      subroutine f2pywrap_ensdam_meanstd_update_meanstd_vector_weight (v&
     &ct, weight, weightsum, mean, msqra, f2py_vct_d0, f2py_weight_d0, f&
     &2py_weightsum_d0, f2py_mean_d0, f2py_msqra_d0)
      use ensdam_meanstd, only : update_meanstd_vector_weight
      integer f2py_vct_d0
      integer f2py_weight_d0
      integer f2py_weightsum_d0
      integer f2py_mean_d0
      integer f2py_msqra_d0
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) weight(f2py_weight_d0)
      real(kind=8) weightsum(f2py_weightsum_d0)
      real(kind=8) mean(f2py_mean_d0)
      real(kind=8) msqra(f2py_msqra_d0)
      call update_meanstd_vector_weight(vct, weight, weightsum, mean, ms&
     &qra)
      end subroutine f2pywrap_ensdam_meanstd_update_meanstd_vector_weigh&
     &t
      
      subroutine f2pyinitensdam_meanstd(f2pysetupfunc)
      use ensdam_meanstd, only : update_meanstd_variable
      use ensdam_meanstd, only : update_meanstd_variable_weight
      interface 
      subroutine f2pywrap_ensdam_meanstd_ensemble_meanstd_vector (ens, m&
     &ean, std, weight, f2py_ens_d0, f2py_ens_d1)
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) mean(size(ens,1))
      real(kind=8) std(size(ens,1))
      real(kind=8) weight(size(ens,1),size(ens,2))
      end subroutine f2pywrap_ensdam_meanstd_ensemble_meanstd_vector 
      subroutine f2pywrap_ensdam_meanstd_ensemble_meanstd_variable (ens,&
     & mean, std, weight, f2py_ens_d0, f2py_weight_d0)
      real(kind=8) mean
      real(kind=8) std
      integer f2py_ens_d0
      integer f2py_weight_d0
      real(kind=8) ens(f2py_ens_d0)
      real(kind=8) weight(f2py_weight_d0)
      end subroutine f2pywrap_ensdam_meanstd_ensemble_meanstd_variable 
      subroutine f2pywrap_ensdam_meanstd_update_meanstd_vector (vct, idx&
     &, mean, msqra, f2py_vct_d0, f2py_mean_d0, f2py_msqra_d0)
      integer idx
      integer f2py_vct_d0
      integer f2py_mean_d0
      integer f2py_msqra_d0
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) mean(f2py_mean_d0)
      real(kind=8) msqra(f2py_msqra_d0)
      end subroutine f2pywrap_ensdam_meanstd_update_meanstd_vector 
      subroutine f2pywrap_ensdam_meanstd_update_meanstd_vector_weight (v&
     &ct, weight, weightsum, mean, msqra, f2py_vct_d0, f2py_weight_d0, f&
     &2py_weightsum_d0, f2py_mean_d0, f2py_msqra_d0)
      integer f2py_vct_d0
      integer f2py_weight_d0
      integer f2py_weightsum_d0
      integer f2py_mean_d0
      integer f2py_msqra_d0
      real(kind=8) vct(f2py_vct_d0)
      real(kind=8) weight(f2py_weight_d0)
      real(kind=8) weightsum(f2py_weightsum_d0)
      real(kind=8) mean(f2py_mean_d0)
      real(kind=8) msqra(f2py_msqra_d0)
      end subroutine f2pywrap_ensdam_meanstd_update_meanstd_vector_weigh&
     &t
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_meanstd_ensemble_meanstd_vector&
     &,f2pywrap_ensdam_meanstd_ensemble_meanstd_variable,f2pywrap_ensdam&
     &_meanstd_update_meanstd_vector,f2pywrap_ensdam_meanstd_update_mean&
     &std_vector_weight,update_meanstd_variable,update_meanstd_variable_&
     &weight)
      end subroutine f2pyinitensdam_meanstd

      subroutine f2pywrap_ensdam_obserror_obserror_logpdf_vector (obserr&
     &or_logpdf_vectorf2pywrap, y, x, sigma, f2py_y_d0, f2py_x_d0, f2py_&
     &sigma_d0)
      use ensdam_obserror, only : obserror_logpdf_vector
      integer f2py_y_d0
      integer f2py_x_d0
      integer f2py_sigma_d0
      real(kind=8) y(f2py_y_d0)
      real(kind=8) x(f2py_x_d0)
      real(kind=8) sigma(f2py_sigma_d0)
      real(kind=8) obserror_logpdf_vectorf2pywrap
      obserror_logpdf_vectorf2pywrap = obserror_logpdf_vector(y, x, sigm&
     &a)
      end subroutine f2pywrap_ensdam_obserror_obserror_logpdf_vector
      subroutine f2pywrap_ensdam_obserror_obserror_logpdf_vector_homogen&
     &eous (obserror_logpdf_vector_homogeneousf2pywrap, y, x, sigma, f2p&
     &y_y_d0, f2py_x_d0)
      use ensdam_obserror, only : obserror_logpdf_vector_homogeneous
      real(kind=8) sigma
      integer f2py_y_d0
      integer f2py_x_d0
      real(kind=8) y(f2py_y_d0)
      real(kind=8) x(f2py_x_d0)
      real(kind=8) obserror_logpdf_vector_homogeneousf2pywrap
      obserror_logpdf_vector_homogeneousf2pywrap = obserror_logpdf_vecto&
     &r_homogeneous(y, x, sigma)
      end subroutine f2pywrap_ensdam_obserror_obserror_logpdf_vector_hom&
     &ogeneous
      subroutine f2pywrap_ensdam_obserror_obserror_logpdf_variable (obse&
     &rror_logpdf_variablef2pywrap, y, x, sigma)
      use ensdam_obserror, only : obserror_logpdf_variable
      real(kind=8) y
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) obserror_logpdf_variablef2pywrap
      obserror_logpdf_variablef2pywrap = obserror_logpdf_variable(y, x, &
     &sigma)
      end subroutine f2pywrap_ensdam_obserror_obserror_logpdf_variable
      subroutine f2pywrap_ensdam_obserror_obserror_cdf_vector (obserror_&
     &cdf_vectorf2pywrap, y, x, sigma, f2py_obserror_cdf_vector_d0, f2py&
     &_y_d0, f2py_x_d0, f2py_sigma_d0)
      use ensdam_obserror, only : obserror_cdf_vector
      integer f2py_obserror_cdf_vector_d0
      integer f2py_y_d0
      integer f2py_x_d0
      integer f2py_sigma_d0
      real(kind=8) y(f2py_y_d0)
      real(kind=8) x(f2py_x_d0)
      real(kind=8) sigma(f2py_sigma_d0)
      real(kind=8) obserror_cdf_vectorf2pywrap(f2py_obserror_cdf_vector_&
     &d0)
      obserror_cdf_vectorf2pywrap = obserror_cdf_vector(y, x, sigma)
      end subroutine f2pywrap_ensdam_obserror_obserror_cdf_vector
      subroutine f2pywrap_ensdam_obserror_obserror_cdf_vector_homogeneou&
     &s (obserror_cdf_vector_homogeneousf2pywrap, y, x, sigma, f2py_obse&
     &rror_cdf_vector_homogeneous_d0, f2py_y_d0, f2py_x_d0)
      use ensdam_obserror, only : obserror_cdf_vector_homogeneous
      real(kind=8) sigma
      integer f2py_obserror_cdf_vector_homogeneous_d0
      integer f2py_y_d0
      integer f2py_x_d0
      real(kind=8) y(f2py_y_d0)
      real(kind=8) x(f2py_x_d0)
      real(kind=8) obserror_cdf_vector_homogeneousf2pywrap(f2py_obserror&
     &_cdf_vector_homogeneous_d0)
      obserror_cdf_vector_homogeneousf2pywrap = obserror_cdf_vector_homo&
     &geneous(y, x, sigma)
      end subroutine f2pywrap_ensdam_obserror_obserror_cdf_vector_homoge&
     &neous
      subroutine f2pywrap_ensdam_obserror_obserror_cdf_variable (obserro&
     &r_cdf_variablef2pywrap, y, x, sigma)
      use ensdam_obserror, only : obserror_cdf_variable
      real(kind=8) y
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) obserror_cdf_variablef2pywrap
      obserror_cdf_variablef2pywrap = obserror_cdf_variable(y, x, sigma)
      end subroutine f2pywrap_ensdam_obserror_obserror_cdf_variable
      subroutine f2pywrap_ensdam_obserror_obserror_sample_vector (obserr&
     &or_sample_vectorf2pywrap, x, sigma, rank_bn, f2py_obserror_sample_&
     &vector_d0, f2py_x_d0, f2py_sigma_d0, f2py_rank_bn_d0)
      use ensdam_obserror, only : obserror_sample_vector
      integer f2py_obserror_sample_vector_d0
      integer f2py_x_d0
      integer f2py_sigma_d0
      integer f2py_rank_bn_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) sigma(f2py_sigma_d0)
      real(kind=8) rank_bn(f2py_rank_bn_d0)
      real(kind=8) obserror_sample_vectorf2pywrap(f2py_obserror_sample_v&
     &ector_d0)
      obserror_sample_vectorf2pywrap = obserror_sample_vector(x, sigma, &
     &rank_bn)
      end subroutine f2pywrap_ensdam_obserror_obserror_sample_vector
      subroutine f2pywrap_ensdam_obserror_obserror_sample_vector_homogen&
     &eous (obserror_sample_vector_homogeneousf2pywrap, x, sigma, rank_b&
     &n, uniform_rank, f2py_x_d0)
      use ensdam_obserror, only : obserror_sample_vector_homogeneous
      real(kind=8) sigma
      real(kind=8) rank_bn
      logical uniform_rank
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) obserror_sample_vector_homogeneousf2pywrap(size(x,1))
      obserror_sample_vector_homogeneousf2pywrap = obserror_sample_vecto&
     &r_homogeneous(x, sigma, rank_bn, uniform_rank)
      end subroutine f2pywrap_ensdam_obserror_obserror_sample_vector_hom&
     &ogeneous
      subroutine f2pywrap_ensdam_obserror_obserror_sample_variable (obse&
     &rror_sample_variablef2pywrap, x, sigma, rank_bn, reuse_last_rank)
      use ensdam_obserror, only : obserror_sample_variable
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) rank_bn
      logical reuse_last_rank
      real(kind=8) obserror_sample_variablef2pywrap
      obserror_sample_variablef2pywrap = obserror_sample_variable(x, sig&
     &ma, rank_bn, reuse_last_rank)
      end subroutine f2pywrap_ensdam_obserror_obserror_sample_variable
      
      subroutine f2pyinitensdam_obserror(f2pysetupfunc)
      interface 
      subroutine f2pywrap_ensdam_obserror_obserror_logpdf_vector (obserr&
     &or_logpdf_vectorf2pywrap, obserror_logpdf_vector, y, x, sigma, f2p&
     &y_y_d0, f2py_x_d0, f2py_sigma_d0)
      real(kind=8) obserror_logpdf_vector
      integer f2py_y_d0
      integer f2py_x_d0
      integer f2py_sigma_d0
      real(kind=8) y(f2py_y_d0)
      real(kind=8) x(f2py_x_d0)
      real(kind=8) sigma(f2py_sigma_d0)
      real(kind=8) obserror_logpdf_vectorf2pywrap
      end subroutine f2pywrap_ensdam_obserror_obserror_logpdf_vector 
      subroutine f2pywrap_ensdam_obserror_obserror_logpdf_vector_homogen&
     &eous (obserror_logpdf_vector_homogeneousf2pywrap, obserror_logpdf_&
     &vector_homogeneous, y, x, sigma, f2py_y_d0, f2py_x_d0)
      real(kind=8) obserror_logpdf_vector_homogeneous
      real(kind=8) sigma
      integer f2py_y_d0
      integer f2py_x_d0
      real(kind=8) y(f2py_y_d0)
      real(kind=8) x(f2py_x_d0)
      real(kind=8) obserror_logpdf_vector_homogeneousf2pywrap
      end subroutine f2pywrap_ensdam_obserror_obserror_logpdf_vector_hom&
     &ogeneous 
      subroutine f2pywrap_ensdam_obserror_obserror_logpdf_variable (obse&
     &rror_logpdf_variablef2pywrap, obserror_logpdf_variable, y, x, sigm&
     &a)
      real(kind=8) obserror_logpdf_variable
      real(kind=8) y
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) obserror_logpdf_variablef2pywrap
      end subroutine f2pywrap_ensdam_obserror_obserror_logpdf_variable 
      subroutine f2pywrap_ensdam_obserror_obserror_cdf_vector (obserror_&
     &cdf_vectorf2pywrap, obserror_cdf_vector, y, x, sigma, f2py_obserro&
     &r_cdf_vector_d0, f2py_y_d0, f2py_x_d0, f2py_sigma_d0)
      integer f2py_obserror_cdf_vector_d0
      integer f2py_y_d0
      integer f2py_x_d0
      integer f2py_sigma_d0
      real(kind=8) y(f2py_y_d0)
      real(kind=8) x(f2py_x_d0)
      real(kind=8) sigma(f2py_sigma_d0)
      real(kind=8) obserror_cdf_vector(f2py_obserror_cdf_vector_d0)
      real(kind=8) obserror_cdf_vectorf2pywrap(f2py_obserror_cdf_vector_&
     &d0)
      end subroutine f2pywrap_ensdam_obserror_obserror_cdf_vector 
      subroutine f2pywrap_ensdam_obserror_obserror_cdf_vector_homogeneou&
     &s (obserror_cdf_vector_homogeneousf2pywrap, obserror_cdf_vector_ho&
     &mogeneous, y, x, sigma, f2py_obserror_cdf_vector_homogeneous_d0, f&
     &2py_y_d0, f2py_x_d0)
      real(kind=8) sigma
      integer f2py_obserror_cdf_vector_homogeneous_d0
      integer f2py_y_d0
      integer f2py_x_d0
      real(kind=8) y(f2py_y_d0)
      real(kind=8) x(f2py_x_d0)
      real(kind=8) obserror_cdf_vector_homogeneous(f2py_obserror_cdf_vec&
     &tor_homogeneous_d0)
      real(kind=8) obserror_cdf_vector_homogeneousf2pywrap(f2py_obserror&
     &_cdf_vector_homogeneous_d0)
      end subroutine f2pywrap_ensdam_obserror_obserror_cdf_vector_homoge&
     &neous 
      subroutine f2pywrap_ensdam_obserror_obserror_cdf_variable (obserro&
     &r_cdf_variablef2pywrap, obserror_cdf_variable, y, x, sigma)
      real(kind=8) obserror_cdf_variable
      real(kind=8) y
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) obserror_cdf_variablef2pywrap
      end subroutine f2pywrap_ensdam_obserror_obserror_cdf_variable 
      subroutine f2pywrap_ensdam_obserror_obserror_sample_vector (obserr&
     &or_sample_vectorf2pywrap, obserror_sample_vector, x, sigma, rank_b&
     &n, f2py_obserror_sample_vector_d0, f2py_x_d0, f2py_sigma_d0, f2py_&
     &rank_bn_d0)
      integer f2py_obserror_sample_vector_d0
      integer f2py_x_d0
      integer f2py_sigma_d0
      integer f2py_rank_bn_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) sigma(f2py_sigma_d0)
      real(kind=8) rank_bn(f2py_rank_bn_d0)
      real(kind=8) obserror_sample_vector(f2py_obserror_sample_vector_d0&
     &)
      real(kind=8) obserror_sample_vectorf2pywrap(f2py_obserror_sample_v&
     &ector_d0)
      end subroutine f2pywrap_ensdam_obserror_obserror_sample_vector 
      subroutine f2pywrap_ensdam_obserror_obserror_sample_vector_homogen&
     &eous (obserror_sample_vector_homogeneousf2pywrap, obserror_sample_&
     &vector_homogeneous, x, sigma, rank_bn, uniform_rank, f2py_x_d0)
      real(kind=8) sigma
      real(kind=8) rank_bn
      logical uniform_rank
      integer f2py_x_d0
      real(kind=8) x(f2py_x_d0)
      real(kind=8) obserror_sample_vector_homogeneous(size(x,1))
      real(kind=8) obserror_sample_vector_homogeneousf2pywrap(size(x,1))
      end subroutine f2pywrap_ensdam_obserror_obserror_sample_vector_hom&
     &ogeneous 
      subroutine f2pywrap_ensdam_obserror_obserror_sample_variable (obse&
     &rror_sample_variablef2pywrap, obserror_sample_variable, x, sigma, &
     &rank_bn, reuse_last_rank)
      real(kind=8) obserror_sample_variable
      real(kind=8) x
      real(kind=8) sigma
      real(kind=8) rank_bn
      logical reuse_last_rank
      real(kind=8) obserror_sample_variablef2pywrap
      end subroutine f2pywrap_ensdam_obserror_obserror_sample_variable
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_obserror_obserror_logpdf_vector&
     &,f2pywrap_ensdam_obserror_obserror_logpdf_vector_homogeneous,f2pyw&
     &rap_ensdam_obserror_obserror_logpdf_variable,f2pywrap_ensdam_obser&
     &ror_obserror_cdf_vector,f2pywrap_ensdam_obserror_obserror_cdf_vect&
     &or_homogeneous,f2pywrap_ensdam_obserror_obserror_cdf_variable,f2py&
     &wrap_ensdam_obserror_obserror_sample_vector,f2pywrap_ensdam_obserr&
     &or_obserror_sample_vector_homogeneous,f2pywrap_ensdam_obserror_obs&
     &error_sample_variable)
      end subroutine f2pyinitensdam_obserror

      subroutine f2pywrap_ensdam_schurprod_schurprod_vector (prod, vct, &
     &f2py_prod_d0)
      use ensdam_schurprod, only : schurprod_vector
      integer f2py_prod_d0
      real(kind=8) prod(f2py_prod_d0)
      real(kind=8) vct(size(prod,1))
      call schurprod_vector(prod, vct)
      end subroutine f2pywrap_ensdam_schurprod_schurprod_vector
      
      subroutine f2pyinitensdam_schurprod(f2pysetupfunc)
      use ensdam_schurprod, only : schurprod_gpmin
      use ensdam_schurprod, only : schurprod_gpmax
      use ensdam_schurprod, only : schurprod_precompute
      use ensdam_schurprod, only : schurprod_tablesize
      use ensdam_schurprod, only : schurprod_variable
      interface 
      subroutine f2pywrap_ensdam_schurprod_schurprod_vector (prod, vct, &
     &f2py_prod_d0)
      integer f2py_prod_d0
      real(kind=8) prod(f2py_prod_d0)
      real(kind=8) vct(size(prod,1))
      end subroutine f2pywrap_ensdam_schurprod_schurprod_vector
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(schurprod_gpmin,schurprod_gpmax,schurprod_preco&
     &mpute,schurprod_tablesize,f2pywrap_ensdam_schurprod_schurprod_vect&
     &or,schurprod_variable)
      end subroutine f2pyinitensdam_schurprod

      subroutine f2pywrap_ensdam_score_crps_crps_score_global (crps, rel&
     &iability, resolution, ens, verif, f2py_ens_d0, f2py_ens_d1)
      use ensdam_score_crps, only : crps_score_global
      real(kind=8) crps
      real(kind=8) reliability
      real(kind=8) resolution
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) verif(size(ens,1))
      call crps_score_global(crps, reliability, resolution, ens, verif)
      end subroutine f2pywrap_ensdam_score_crps_crps_score_global
      subroutine f2pywrap_ensdam_score_crps_crps_score_partition (crps, &
     &reliability, resolution, ens, verif, partition, f2py_crps_d0, f2py&
     &_ens_d0, f2py_ens_d1)
      use ensdam_score_crps, only : crps_score_partition
      integer f2py_crps_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) crps(f2py_crps_d0)
      real(kind=8) reliability(size(crps,1))
      real(kind=8) resolution(size(crps,1))
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) verif(size(ens,1))
      integer partition(size(ens,1))
      call crps_score_partition(crps, reliability, resolution, ens, veri&
     &f, partition)
      end subroutine f2pywrap_ensdam_score_crps_crps_score_partition
      subroutine f2pywrap_ensdam_score_crps_crps_cumul (ens, a, aa, bb, &
     &f2py_ens_d0)
      use ensdam_score_crps, only : crps_cumul
                use ensdam_anaqua
      real(kind=8) a
      integer f2py_ens_d0
      real(kind=8) ens(f2py_ens_d0)
      real(kind=8) aa(1)
      real(kind=8) bb(1)
      call crps_cumul(ens, a, aa, bb)
      end subroutine f2pywrap_ensdam_score_crps_crps_cumul
      
      subroutine f2pyinitensdam_score_crps(f2pysetupfunc)
      use ensdam_score_crps, only : crps_missing_value
      use ensdam_score_crps, only : mpi_comm_score_crps
      use ensdam_score_crps, only : crps_final
      interface 
      subroutine f2pywrap_ensdam_score_crps_crps_score_global (crps, rel&
     &iability, resolution, ens, verif, f2py_ens_d0, f2py_ens_d1)
      real(kind=8) crps
      real(kind=8) reliability
      real(kind=8) resolution
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) verif(size(ens,1))
      end subroutine f2pywrap_ensdam_score_crps_crps_score_global 
      subroutine f2pywrap_ensdam_score_crps_crps_score_partition (crps, &
     &reliability, resolution, ens, verif, partition, f2py_crps_d0, f2py&
     &_ens_d0, f2py_ens_d1)
      integer f2py_crps_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) crps(f2py_crps_d0)
      real(kind=8) reliability(size(crps,1))
      real(kind=8) resolution(size(crps,1))
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) verif(size(ens,1))
      integer partition(size(ens,1))
      end subroutine f2pywrap_ensdam_score_crps_crps_score_partition 
      subroutine f2pywrap_ensdam_score_crps_crps_cumul (ens, a, aa, bb, &
     &f2py_ens_d0)
      real(kind=8) a
      integer f2py_ens_d0
      real(kind=8) ens(f2py_ens_d0)
      real(kind=8) aa(1)
      real(kind=8) bb(1)
      end subroutine f2pywrap_ensdam_score_crps_crps_cumul
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(crps_missing_value,mpi_comm_score_crps,f2pywrap&
     &_ensdam_score_crps_crps_score_global,f2pywrap_ensdam_score_crps_cr&
     &ps_score_partition,f2pywrap_ensdam_score_crps_crps_cumul,crps_fina&
     &l)
      end subroutine f2pyinitensdam_score_crps

      subroutine f2pywrap_ensdam_score_entropy_events_score (score, ens,&
     & pref, events_outcome, f2py_score_d0, f2py_ens_d0, f2py_ens_d1, f2&
     &py_pref_d0, f2py_pref_d1)
      use ensdam_score_entropy, only : events_score
      external events_outcome
      integer f2py_score_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_pref_d0
      integer f2py_pref_d1
      real(kind=8) score(f2py_score_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) pref(f2py_pref_d0,f2py_pref_d1)
      call events_score(score, ens, pref, events_outcome)
      end subroutine f2pywrap_ensdam_score_entropy_events_score
      subroutine f2pywrap_ensdam_score_entropy_events_relative_entropy (&
     &relative_entropy, ens, pref, events_outcome, f2py_relative_entropy&
     &_d0, f2py_ens_d0, f2py_ens_d1, f2py_pref_d0, f2py_pref_d1)
      use ensdam_score_entropy, only : events_relative_entropy
      external events_outcome
      integer f2py_relative_entropy_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_pref_d0
      integer f2py_pref_d1
      real(kind=8) relative_entropy(f2py_relative_entropy_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) pref(f2py_pref_d0,f2py_pref_d1)
      call events_relative_entropy(relative_entropy, ens, pref, events_o&
     &utcome)
      end subroutine f2pywrap_ensdam_score_entropy_events_relative_entro&
     &py
      subroutine f2pywrap_ensdam_score_entropy_events_cross_entropy (cro&
     &ss_entropy, entropy, ens, pref, events_outcome, f2py_cross_entropy&
     &_d0, f2py_entropy_d0, f2py_ens_d0, f2py_ens_d1, f2py_pref_d0, f2py&
     &_pref_d1)
      use ensdam_score_entropy, only : events_cross_entropy
      external events_outcome
      integer f2py_cross_entropy_d0
      integer f2py_entropy_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_pref_d0
      integer f2py_pref_d1
      real(kind=8) cross_entropy(f2py_cross_entropy_d0)
      real(kind=8) entropy(f2py_entropy_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) pref(f2py_pref_d0,f2py_pref_d1)
      call events_cross_entropy(cross_entropy, entropy, ens, pref, event&
     &s_outcome)
      end subroutine f2pywrap_ensdam_score_entropy_events_cross_entropy
      subroutine f2pywrap_ensdam_score_entropy_events_entropy (entropy, &
     &ens, events_outcome, number_outcome, f2py_entropy_d0, f2py_ens_d0,&
     & f2py_ens_d1)
      use ensdam_score_entropy, only : events_entropy
      external events_outcome
      integer number_outcome
      integer f2py_entropy_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) entropy(f2py_entropy_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      call events_entropy(entropy, ens, events_outcome, number_outcome)
      end subroutine f2pywrap_ensdam_score_entropy_events_entropy
      subroutine f2pywrap_ensdam_score_entropy_events_probability (pens,&
     & ens, events_outcome, f2py_pens_d0, f2py_pens_d1, f2py_ens_d0, f2p&
     &y_ens_d1)
      use ensdam_score_entropy, only : events_probability
      external events_outcome
      integer f2py_pens_d0
      integer f2py_pens_d1
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) pens(f2py_pens_d0,f2py_pens_d1)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      call events_probability(pens, ens, events_outcome)
      end subroutine f2pywrap_ensdam_score_entropy_events_probability
      
      subroutine f2pyinitensdam_score_entropy(f2pysetupfunc)
      use ensdam_score_entropy, only : mpi_comm_score_entropy
      use ensdam_score_entropy, only : score_entropy_base
      interface 
      subroutine f2pywrap_ensdam_score_entropy_events_score (score, ens,&
     & pref, events_outcome, f2py_score_d0, f2py_ens_d0, f2py_ens_d1, f2&
     &py_pref_d0, f2py_pref_d1)
      external events_outcome
      integer f2py_score_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_pref_d0
      integer f2py_pref_d1
      real(kind=8) score(f2py_score_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) pref(f2py_pref_d0,f2py_pref_d1)
      end subroutine f2pywrap_ensdam_score_entropy_events_score 
      subroutine f2pywrap_ensdam_score_entropy_events_relative_entropy (&
     &relative_entropy, ens, pref, events_outcome, f2py_relative_entropy&
     &_d0, f2py_ens_d0, f2py_ens_d1, f2py_pref_d0, f2py_pref_d1)
      external events_outcome
      integer f2py_relative_entropy_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_pref_d0
      integer f2py_pref_d1
      real(kind=8) relative_entropy(f2py_relative_entropy_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) pref(f2py_pref_d0,f2py_pref_d1)
      end subroutine f2pywrap_ensdam_score_entropy_events_relative_entro&
     &py 
      subroutine f2pywrap_ensdam_score_entropy_events_cross_entropy (cro&
     &ss_entropy, entropy, ens, pref, events_outcome, f2py_cross_entropy&
     &_d0, f2py_entropy_d0, f2py_ens_d0, f2py_ens_d1, f2py_pref_d0, f2py&
     &_pref_d1)
      external events_outcome
      integer f2py_cross_entropy_d0
      integer f2py_entropy_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_pref_d0
      integer f2py_pref_d1
      real(kind=8) cross_entropy(f2py_cross_entropy_d0)
      real(kind=8) entropy(f2py_entropy_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) pref(f2py_pref_d0,f2py_pref_d1)
      end subroutine f2pywrap_ensdam_score_entropy_events_cross_entropy 
      subroutine f2pywrap_ensdam_score_entropy_events_entropy (entropy, &
     &ens, events_outcome, number_outcome, f2py_entropy_d0, f2py_ens_d0,&
     & f2py_ens_d1)
      external events_outcome
      integer number_outcome
      integer f2py_entropy_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) entropy(f2py_entropy_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      end subroutine f2pywrap_ensdam_score_entropy_events_entropy 
      subroutine f2pywrap_ensdam_score_entropy_events_probability (pens,&
     & ens, events_outcome, f2py_pens_d0, f2py_pens_d1, f2py_ens_d0, f2p&
     &y_ens_d1)
      external events_outcome
      integer f2py_pens_d0
      integer f2py_pens_d1
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) pens(f2py_pens_d0,f2py_pens_d1)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      end subroutine f2pywrap_ensdam_score_entropy_events_probability
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(mpi_comm_score_entropy,score_entropy_base,f2pyw&
     &rap_ensdam_score_entropy_events_score,f2pywrap_ensdam_score_entrop&
     &y_events_relative_entropy,f2pywrap_ensdam_score_entropy_events_cro&
     &ss_entropy,f2pywrap_ensdam_score_entropy_events_entropy,f2pywrap_e&
     &nsdam_score_entropy_events_probability)
      end subroutine f2pyinitensdam_score_entropy

      subroutine f2pywrap_ensdam_score_optimality_optimality_score_globa&
     &l (ens_optimality, ens_optimality_bias, ens_optimality_spread, ens&
     &, obs, cdf_obs, f2py_ens_d0, f2py_ens_d1, f2py_obs_d0)
      use ensdam_score_optimality, only : optimality_score_global
                use ensdam_score_optimality, only: callback_cdf_obs
      procedure(callback_cdf_obs) :: cdf_obs
      real(kind=8) ens_optimality
      real(kind=8) ens_optimality_bias
      real(kind=8) ens_optimality_spread
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_obs_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) obs(f2py_obs_d0)
      call optimality_score_global(ens_optimality, ens_optimality_bias, &
     &ens_optimality_spread, ens, obs, cdf_obs)
      end subroutine f2pywrap_ensdam_score_optimality_optimality_score_g&
     &lobal
      subroutine f2pywrap_ensdam_score_optimality_optimality_score_parti&
     &tion (ens_optimality, ens_optimality_bias, ens_optimality_spread, &
     &ens, obs, partition, cdf_obs, f2py_ens_optimality_d0, f2py_ens_opt&
     &imality_bias_d0, f2py_ens_optimality_spread_d0, f2py_ens_d0, f2py_&
     &ens_d1, f2py_obs_d0, f2py_partition_d0)
      use ensdam_score_optimality, only : optimality_score_partition
                use ensdam_score_optimality, only: callback_cdf_obs
      procedure(callback_cdf_obs) :: cdf_obs
      integer f2py_ens_optimality_d0
      integer f2py_ens_optimality_bias_d0
      integer f2py_ens_optimality_spread_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_obs_d0
      integer f2py_partition_d0
      real(kind=8) ens_optimality(f2py_ens_optimality_d0)
      real(kind=8) ens_optimality_bias(f2py_ens_optimality_bias_d0)
      real(kind=8) ens_optimality_spread(f2py_ens_optimality_spread_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) obs(f2py_obs_d0)
      integer partition(f2py_partition_d0)
      call optimality_score_partition(ens_optimality, ens_optimality_bia&
     &s, ens_optimality_spread, ens, obs, partition, cdf_obs)
      end subroutine f2pywrap_ensdam_score_optimality_optimality_score_p&
     &artition
      subroutine f2pywrap_ensdam_score_optimality_optimality_cumul (e, o&
     &, idx, mean, sqrs, cdf_obs, f2py_e_d0)
      use ensdam_score_optimality, only : optimality_cumul
                use ensdam_score_optimality, only: callback_cdf_obs
                use ensdam_meanstd
                use ensdam_stoutil
      procedure(callback_cdf_obs) :: cdf_obs
      real(kind=8) o
      integer idx
      real(kind=8) mean
      real(kind=8) sqrs
      integer f2py_e_d0
      real(kind=8) e(f2py_e_d0)
      call optimality_cumul(e, o, idx, mean, sqrs, cdf_obs)
      end subroutine f2pywrap_ensdam_score_optimality_optimality_cumul
      
      subroutine f2pyinitensdam_score_optimality(f2pysetupfunc)
      interface 
      subroutine f2pywrap_ensdam_score_optimality_optimality_score_globa&
     &l (ens_optimality, ens_optimality_bias, ens_optimality_spread, ens&
     &, obs, cdf_obs, f2py_ens_d0, f2py_ens_d1, f2py_obs_d0)
      external cdf_obs
      real(kind=8) ens_optimality
      real(kind=8) ens_optimality_bias
      real(kind=8) ens_optimality_spread
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_obs_d0
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) obs(f2py_obs_d0)
      end subroutine f2pywrap_ensdam_score_optimality_optimality_score_g&
     &lobal 
      subroutine f2pywrap_ensdam_score_optimality_optimality_score_parti&
     &tion (ens_optimality, ens_optimality_bias, ens_optimality_spread, &
     &ens, obs, partition, cdf_obs, f2py_ens_optimality_d0, f2py_ens_opt&
     &imality_bias_d0, f2py_ens_optimality_spread_d0, f2py_ens_d0, f2py_&
     &ens_d1, f2py_obs_d0, f2py_partition_d0)
      external cdf_obs
      integer f2py_ens_optimality_d0
      integer f2py_ens_optimality_bias_d0
      integer f2py_ens_optimality_spread_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      integer f2py_obs_d0
      integer f2py_partition_d0
      real(kind=8) ens_optimality(f2py_ens_optimality_d0)
      real(kind=8) ens_optimality_bias(f2py_ens_optimality_bias_d0)
      real(kind=8) ens_optimality_spread(f2py_ens_optimality_spread_d0)
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) obs(f2py_obs_d0)
      integer partition(f2py_partition_d0)
      end subroutine f2pywrap_ensdam_score_optimality_optimality_score_p&
     &artition 
      subroutine f2pywrap_ensdam_score_optimality_optimality_cumul (e, o&
     &, idx, mean, sqrs, cdf_obs, f2py_e_d0)
      external cdf_obs
      real(kind=8) o
      integer idx
      real(kind=8) mean
      real(kind=8) sqrs
      integer f2py_e_d0
      real(kind=8) e(f2py_e_d0)
      end subroutine f2pywrap_ensdam_score_optimality_optimality_cumul
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_score_optimality_optimality_sco&
     &re_global,f2pywrap_ensdam_score_optimality_optimality_score_partit&
     &ion,f2pywrap_ensdam_score_optimality_optimality_cumul)
      end subroutine f2pyinitensdam_score_optimality

      subroutine f2pywrap_ensdam_score_rcrv_rcrv_score_global (ens_bias,&
     & ens_spread, ens, verif, f2py_ens_d0, f2py_ens_d1)
      use ensdam_score_rcrv, only : rcrv_score_global
      real(kind=8) ens_bias
      real(kind=8) ens_spread
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) verif(size(ens,1))
      call rcrv_score_global(ens_bias, ens_spread, ens, verif)
      end subroutine f2pywrap_ensdam_score_rcrv_rcrv_score_global
      subroutine f2pywrap_ensdam_score_rcrv_rcrv_score_partition (ens_bi&
     &as, ens_spread, ens, verif, partition, f2py_ens_bias_d0, f2py_ens_&
     &d0, f2py_ens_d1)
      use ensdam_score_rcrv, only : rcrv_score_partition
      integer f2py_ens_bias_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) ens_bias(f2py_ens_bias_d0)
      real(kind=8) ens_spread(size(ens_bias,1))
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) verif(size(ens,1))
      integer partition(size(ens,1))
      call rcrv_score_partition(ens_bias, ens_spread, ens, verif, partit&
     &ion)
      end subroutine f2pywrap_ensdam_score_rcrv_rcrv_score_partition
      subroutine f2pywrap_ensdam_score_rcrv_rcrv_cumul (e, a, idx, mean,&
     & sqrs, f2py_e_d0)
      use ensdam_score_rcrv, only : rcrv_cumul
                use ensdam_anatra
                use ensdam_meanstd
                use ensdam_anaqua
                use ensdam_stoutil
      real(kind=8) a
      integer idx
      real(kind=8) mean
      real(kind=8) sqrs
      integer f2py_e_d0
      real(kind=8) e(f2py_e_d0)
      call rcrv_cumul(e, a, idx, mean, sqrs)
      end subroutine f2pywrap_ensdam_score_rcrv_rcrv_cumul
      
      subroutine f2pyinitensdam_score_rcrv(f2pysetupfunc)
      use ensdam_score_rcrv, only : mpi_comm_score_rcrv
      use ensdam_score_rcrv, only : rcrv_number_of_quantiles
      use ensdam_score_rcrv, only : rcrv_with_anamorphosis
      use ensdam_score_rcrv, only : rcrv_missing_value
      interface 
      subroutine f2pywrap_ensdam_score_rcrv_rcrv_score_global (ens_bias,&
     & ens_spread, ens, verif, f2py_ens_d0, f2py_ens_d1)
      real(kind=8) ens_bias
      real(kind=8) ens_spread
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) verif(size(ens,1))
      end subroutine f2pywrap_ensdam_score_rcrv_rcrv_score_global 
      subroutine f2pywrap_ensdam_score_rcrv_rcrv_score_partition (ens_bi&
     &as, ens_spread, ens, verif, partition, f2py_ens_bias_d0, f2py_ens_&
     &d0, f2py_ens_d1)
      integer f2py_ens_bias_d0
      integer f2py_ens_d0
      integer f2py_ens_d1
      real(kind=8) ens_bias(f2py_ens_bias_d0)
      real(kind=8) ens_spread(size(ens_bias,1))
      real(kind=8) ens(f2py_ens_d0,f2py_ens_d1)
      real(kind=8) verif(size(ens,1))
      integer partition(size(ens,1))
      end subroutine f2pywrap_ensdam_score_rcrv_rcrv_score_partition 
      subroutine f2pywrap_ensdam_score_rcrv_rcrv_cumul (e, a, idx, mean,&
     & sqrs, f2py_e_d0)
      real(kind=8) a
      integer idx
      real(kind=8) mean
      real(kind=8) sqrs
      integer f2py_e_d0
      real(kind=8) e(f2py_e_d0)
      end subroutine f2pywrap_ensdam_score_rcrv_rcrv_cumul
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(mpi_comm_score_rcrv,rcrv_number_of_quantiles,rc&
     &rv_with_anamorphosis,rcrv_missing_value,f2pywrap_ensdam_score_rcrv&
     &_rcrv_score_global,f2pywrap_ensdam_score_rcrv_rcrv_score_partition&
     &,f2pywrap_ensdam_score_rcrv_rcrv_cumul)
      end subroutine f2pyinitensdam_score_rcrv

      subroutine f2pywrap_ensdam_spharea_mesh_area (lon, lat, area, f2py&
     &_lon_d0, f2py_lon_d1)
      use ensdam_spharea, only : mesh_area
      integer f2py_lon_d0
      integer f2py_lon_d1
      real(kind=8) lon(f2py_lon_d0,f2py_lon_d1)
      real(kind=8) lat(size(lon,1),size(lon,2))
      real(kind=8) area(size(lon,1)-1,size(lon,2)-2)
      call mesh_area(lon, lat, area)
      end subroutine f2pywrap_ensdam_spharea_mesh_area
      
      subroutine f2pyinitensdam_spharea(f2pysetupfunc)
      interface 
      subroutine f2pywrap_ensdam_spharea_mesh_area (lon, lat, area, f2py&
     &_lon_d0, f2py_lon_d1)
      integer f2py_lon_d0
      integer f2py_lon_d1
      real(kind=8) lon(f2py_lon_d0,f2py_lon_d1)
      real(kind=8) lat(size(lon,1),size(lon,2))
      real(kind=8) area(size(lon,1)-1,size(lon,2)-2)
      end subroutine f2pywrap_ensdam_spharea_mesh_area
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_spharea_mesh_area)
      end subroutine f2pyinitensdam_spharea

      subroutine f2pywrap_ensdam_sphylm_proj_ylm (kproj, ktab, klon, kla&
     &t, f2py_kproj_d0, f2py_kproj_d1, f2py_ktab_d0, f2py_klon_d0, f2py_&
     &klat_d0)
      use ensdam_sphylm, only : proj_ylm
      integer f2py_kproj_d0
      integer f2py_kproj_d1
      integer f2py_ktab_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      real(kind=8) kproj(f2py_kproj_d0,f2py_kproj_d1)
      real(kind=8) ktab(f2py_ktab_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      call proj_ylm(kproj, ktab, klon, klat)
      end subroutine f2pywrap_ensdam_sphylm_proj_ylm
      subroutine f2pywrap_ensdam_sphylm_back_ylm (kproj, ktab, klon, kla&
     &t, f2py_kproj_d0, f2py_kproj_d1, f2py_ktab_d0, f2py_klon_d0, f2py_&
     &klat_d0)
      use ensdam_sphylm, only : back_ylm
      integer f2py_kproj_d0
      integer f2py_kproj_d1
      integer f2py_ktab_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      real(kind=8) kproj(f2py_kproj_d0,f2py_kproj_d1)
      real(kind=8) ktab(f2py_ktab_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      call back_ylm(kproj, ktab, klon, klat)
      end subroutine f2pywrap_ensdam_sphylm_back_ylm
      subroutine f2pywrap_ensdam_sphylm_back_ylm_loc (kproj, ktab, klon,&
     & klat, kl0, kl1, f2py_kproj_d0, f2py_kproj_d1, f2py_ktab_d0, f2py_&
     &klon_d0, f2py_klat_d0)
      use ensdam_sphylm, only : back_ylm_loc
      integer kl0
      integer kl1
      integer f2py_kproj_d0
      integer f2py_kproj_d1
      integer f2py_ktab_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      real(kind=8) kproj(f2py_kproj_d0,f2py_kproj_d1)
      real(kind=8) ktab(f2py_ktab_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      call back_ylm_loc(kproj, ktab, klon, klat, kl0, kl1)
      end subroutine f2pywrap_ensdam_sphylm_back_ylm_loc
      subroutine f2pywrap_ensdam_sphylm_regr_ylm (kregr, kwei, kobs, klo&
     &n, klat, kobswei, f2py_kregr_d0, f2py_kregr_d1, f2py_kwei_d0, f2py&
     &_kwei_d1, f2py_kobs_d0, f2py_klon_d0, f2py_klat_d0, f2py_kobswei_d&
     &0)
      use ensdam_sphylm, only : regr_ylm
      integer f2py_kregr_d0
      integer f2py_kregr_d1
      integer f2py_kwei_d0
      integer f2py_kwei_d1
      integer f2py_kobs_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      integer f2py_kobswei_d0
      real(kind=8) kregr(f2py_kregr_d0,f2py_kregr_d1)
      real(kind=8) kwei(f2py_kwei_d0,f2py_kwei_d1)
      real(kind=8) kobs(f2py_kobs_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      real(kind=8) kobswei(f2py_kobswei_d0)
      call regr_ylm(kregr, kwei, kobs, klon, klat, kobswei)
      end subroutine f2pywrap_ensdam_sphylm_regr_ylm
      subroutine f2pywrap_ensdam_sphylm_disp_ylm (ktab, klon, klat, kl, &
     &km, f2py_ktab_d0, f2py_klon_d0, f2py_klat_d0)
      use ensdam_sphylm, only : disp_ylm
      integer kl
      integer km
      integer f2py_ktab_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      real(kind=8) ktab(f2py_ktab_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      call disp_ylm(ktab, klon, klat, kl, km)
      end subroutine f2pywrap_ensdam_sphylm_disp_ylm
      subroutine f2pywrap_ensdam_sphylm_ylm (ylmf2pywrap, kl, km, klon, &
     &klat)
      use ensdam_sphylm, only : ylm
      integer kl
      integer km
      real(kind=8) klon
      real(kind=8) klat
      real(kind=8) ylmf2pywrap
      ylmf2pywrap = ylm(kl, km, klon, klat)
      end subroutine f2pywrap_ensdam_sphylm_ylm
      
      subroutine f2pyinitensdam_sphylm(f2pysetupfunc)
      use ensdam_sphylm, only : regr_epsilon
      use ensdam_sphylm, only : regr_overlap
      use ensdam_sphylm, only : regr_maxiter
      use ensdam_sphylm, only : regr_type
      use ensdam_sphylm, only : mpi_comm_sphylm
      use ensdam_sphylm, only : external_vector_decomposition
      use ensdam_sphylm, only : regr_rho
      use ensdam_sphylm, only : regr_maxbloc
      use ensdam_sphylm, only : init_ylm
      use ensdam_sphylm, only : init_regr_ylm
      interface 
      subroutine f2pywrap_ensdam_sphylm_proj_ylm (kproj, ktab, klon, kla&
     &t, f2py_kproj_d0, f2py_kproj_d1, f2py_ktab_d0, f2py_klon_d0, f2py_&
     &klat_d0)
      integer f2py_kproj_d0
      integer f2py_kproj_d1
      integer f2py_ktab_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      real(kind=8) kproj(f2py_kproj_d0,f2py_kproj_d1)
      real(kind=8) ktab(f2py_ktab_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      end subroutine f2pywrap_ensdam_sphylm_proj_ylm 
      subroutine f2pywrap_ensdam_sphylm_back_ylm (kproj, ktab, klon, kla&
     &t, f2py_kproj_d0, f2py_kproj_d1, f2py_ktab_d0, f2py_klon_d0, f2py_&
     &klat_d0)
      integer f2py_kproj_d0
      integer f2py_kproj_d1
      integer f2py_ktab_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      real(kind=8) kproj(f2py_kproj_d0,f2py_kproj_d1)
      real(kind=8) ktab(f2py_ktab_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      end subroutine f2pywrap_ensdam_sphylm_back_ylm 
      subroutine f2pywrap_ensdam_sphylm_back_ylm_loc (kproj, ktab, klon,&
     & klat, kl0, kl1, f2py_kproj_d0, f2py_kproj_d1, f2py_ktab_d0, f2py_&
     &klon_d0, f2py_klat_d0)
      integer kl0
      integer kl1
      integer f2py_kproj_d0
      integer f2py_kproj_d1
      integer f2py_ktab_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      real(kind=8) kproj(f2py_kproj_d0,f2py_kproj_d1)
      real(kind=8) ktab(f2py_ktab_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      end subroutine f2pywrap_ensdam_sphylm_back_ylm_loc 
      subroutine f2pywrap_ensdam_sphylm_regr_ylm (kregr, kwei, kobs, klo&
     &n, klat, kobswei, f2py_kregr_d0, f2py_kregr_d1, f2py_kwei_d0, f2py&
     &_kwei_d1, f2py_kobs_d0, f2py_klon_d0, f2py_klat_d0, f2py_kobswei_d&
     &0)
      integer f2py_kregr_d0
      integer f2py_kregr_d1
      integer f2py_kwei_d0
      integer f2py_kwei_d1
      integer f2py_kobs_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      integer f2py_kobswei_d0
      real(kind=8) kregr(f2py_kregr_d0,f2py_kregr_d1)
      real(kind=8) kwei(f2py_kwei_d0,f2py_kwei_d1)
      real(kind=8) kobs(f2py_kobs_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      real(kind=8) kobswei(f2py_kobswei_d0)
      end subroutine f2pywrap_ensdam_sphylm_regr_ylm 
      subroutine f2pywrap_ensdam_sphylm_disp_ylm (ktab, klon, klat, kl, &
     &km, f2py_ktab_d0, f2py_klon_d0, f2py_klat_d0)
      integer kl
      integer km
      integer f2py_ktab_d0
      integer f2py_klon_d0
      integer f2py_klat_d0
      real(kind=8) ktab(f2py_ktab_d0)
      real(kind=8) klon(f2py_klon_d0)
      real(kind=8) klat(f2py_klat_d0)
      end subroutine f2pywrap_ensdam_sphylm_disp_ylm 
      subroutine f2pywrap_ensdam_sphylm_ylm (ylmf2pywrap, ylm, kl, km, k&
     &lon, klat)
      real(kind=8) ylm
      integer kl
      integer km
      real(kind=8) klon
      real(kind=8) klat
      real(kind=8) ylmf2pywrap
      end subroutine f2pywrap_ensdam_sphylm_ylm
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(regr_epsilon,regr_overlap,regr_maxiter,regr_typ&
     &e,mpi_comm_sphylm,external_vector_decomposition,regr_rho,regr_maxb&
     &loc,init_ylm,init_regr_ylm,f2pywrap_ensdam_sphylm_proj_ylm,f2pywra&
     &p_ensdam_sphylm_back_ylm,f2pywrap_ensdam_sphylm_back_ylm_loc,f2pyw&
     &rap_ensdam_sphylm_regr_ylm,f2pywrap_ensdam_sphylm_disp_ylm,f2pywra&
     &p_ensdam_sphylm_ylm)
      end subroutine f2pyinitensdam_sphylm

      
      subroutine f2pyinitensdam_stoanam(f2pysetupfunc)
      use ensdam_stoanam, only : gprod_to_gau
      use ensdam_stoanam, only : gau_to_gam
      use ensdam_stoanam, only : gau_to_beta
      external f2pysetupfunc
      call f2pysetupfunc(gprod_to_gau,gau_to_gam,gau_to_beta)
      end subroutine f2pyinitensdam_stoanam

      
      subroutine f2pyinitensdam_stogprod(f2pysetupfunc)
      use ensdam_stogprod, only : fnprod
      external f2pysetupfunc
      call f2pysetupfunc(fnprod)
      end subroutine f2pyinitensdam_stogprod

      subroutine f2pywrap_ensdam_storfg_gen_field_2s_new (ranfield, lon,&
     & lat, pow_spect, lmin, lmax, f2py_ranfield_d0)
      use ensdam_storfg, only : gen_field_2s_new
                use ensdam_storfg, only: fun_pow_spect_sph
      procedure(fun_pow_spect_sph) :: pow_spect
      integer lmin
      integer lmax
      integer f2py_ranfield_d0
      real(kind=8) ranfield(f2py_ranfield_d0)
      real(kind=8) lon(size(ranfield,1))
      real(kind=8) lat(size(ranfield,1))
      call gen_field_2s_new(ranfield, lon, lat, pow_spect, lmin, lmax)
      end subroutine f2pywrap_ensdam_storfg_gen_field_2s_new
      subroutine f2pywrap_ensdam_storfg_gen_field_2s_new2 (ranfield, lon&
     &, lat, pow_spect, lmin, lmax, f2py_ranfield_d0, f2py_ranfield_d1)
      use ensdam_storfg, only : gen_field_2s_new2
                use ensdam_storfg, only: fun_pow_spect_sph
      procedure(fun_pow_spect_sph) :: pow_spect
      integer lmin
      integer lmax
      integer f2py_ranfield_d0
      integer f2py_ranfield_d1
      real(kind=8) ranfield(f2py_ranfield_d0,f2py_ranfield_d1)
      real(kind=8) lon(size(ranfield,1),size(ranfield,2))
      real(kind=8) lat(size(ranfield,1),size(ranfield,2))
      call gen_field_2s_new2(ranfield, lon, lat, pow_spect, lmin, lmax)
      end subroutine f2pywrap_ensdam_storfg_gen_field_2s_new2
      
      subroutine f2pyinitensdam_storfg(f2pysetupfunc)
      use ensdam_storfg, only : mpi_comm_storfg
      use ensdam_storfg, only : storfg_ylm_resolution
      interface 
      subroutine f2pywrap_ensdam_storfg_gen_field_2s_new (ranfield, lon,&
     & lat, pow_spect, lmin, lmax, f2py_ranfield_d0)
      external pow_spect
      integer lmin
      integer lmax
      integer f2py_ranfield_d0
      real(kind=8) ranfield(f2py_ranfield_d0)
      real(kind=8) lon(size(ranfield,1))
      real(kind=8) lat(size(ranfield,1))
      end subroutine f2pywrap_ensdam_storfg_gen_field_2s_new 
      subroutine f2pywrap_ensdam_storfg_gen_field_2s_new2 (ranfield, lon&
     &, lat, pow_spect, lmin, lmax, f2py_ranfield_d0, f2py_ranfield_d1)
      external pow_spect
      integer lmin
      integer lmax
      integer f2py_ranfield_d0
      integer f2py_ranfield_d1
      real(kind=8) ranfield(f2py_ranfield_d0,f2py_ranfield_d1)
      real(kind=8) lon(size(ranfield,1),size(ranfield,2))
      real(kind=8) lat(size(ranfield,1),size(ranfield,2))
      end subroutine f2pywrap_ensdam_storfg_gen_field_2s_new2
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(mpi_comm_storfg,storfg_ylm_resolution,f2pywrap_&
     &ensdam_storfg_gen_field_2s_new,f2pywrap_ensdam_storfg_gen_field_2s&
     &_new2)
      end subroutine f2pyinitensdam_storfg

      subroutine f2pywrap_ensdam_storng_kiss (kissf2pywrap)
      use ensdam_storng, only : kiss
      integer(kind=8) kissf2pywrap
      kissf2pywrap = kiss()
      end subroutine f2pywrap_ensdam_storng_kiss
      subroutine f2pywrap_ensdam_storng_kiss_sample (a, n, k, f2py_a_d0)
      use ensdam_storng, only : kiss_sample
      integer n
      integer k
      integer f2py_a_d0
      integer a(f2py_a_d0)
      call kiss_sample(a, n, k)
      end subroutine f2pywrap_ensdam_storng_kiss_sample
      
      subroutine f2pyinitensdam_storng(f2pysetupfunc)
      use ensdam_storng, only : kiss_seed
      use ensdam_storng, only : kiss_reset
      use ensdam_storng, only : kiss_check
      use ensdam_storng, only : kiss_save
      use ensdam_storng, only : kiss_load
      use ensdam_storng, only : kiss_uniform
      use ensdam_storng, only : kiss_gaussian
      use ensdam_storng, only : kiss_gamma
      use ensdam_storng, only : kiss_beta
      interface 
      subroutine f2pywrap_ensdam_storng_kiss (kissf2pywrap, kiss)
      integer(kind=8) kiss
      integer(kind=8) kissf2pywrap
      end subroutine f2pywrap_ensdam_storng_kiss 
      subroutine f2pywrap_ensdam_storng_kiss_sample (a, n, k, f2py_a_d0)
      integer n
      integer k
      integer f2py_a_d0
      integer a(f2py_a_d0)
      end subroutine f2pywrap_ensdam_storng_kiss_sample
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_storng_kiss,kiss_seed,kiss_rese&
     &t,kiss_check,kiss_save,kiss_load,kiss_uniform,kiss_gaussian,kiss_g&
     &amma,kiss_beta,f2pywrap_ensdam_storng_kiss_sample)
      end subroutine f2pyinitensdam_storng

      subroutine f2pywrap_ensdam_stotge_ranv_tg (tgvsmpl, matarm, vecbm,&
     & f2py_tgvsmpl_d0, f2py_tgvsmpl_d1, f2py_matarm_d1)
      use ensdam_stotge, only : ranv_tg
      integer f2py_tgvsmpl_d0
      integer f2py_tgvsmpl_d1
      integer f2py_matarm_d1
      real(kind=8) tgvsmpl(f2py_tgvsmpl_d0,f2py_tgvsmpl_d1)
      real(kind=8) matarm(size(tgvsmpl,2),f2py_matarm_d1)
      real(kind=8) vecbm(size(matarm,2))
      call ranv_tg(tgvsmpl, matarm, vecbm)
      end subroutine f2pywrap_ensdam_stotge_ranv_tg
      subroutine f2pywrap_ensdam_stotge_ran_tg (tgsmpl, aa, bb, f2py_tgs&
     &mpl_d0)
      use ensdam_stotge, only : ran_tg
      real(kind=8) aa
      real(kind=8) bb
      integer f2py_tgsmpl_d0
      real(kind=8) tgsmpl(f2py_tgsmpl_d0)
      call ran_tg(tgsmpl, aa, bb)
      end subroutine f2pywrap_ensdam_stotge_ran_tg
      
      subroutine f2pyinitensdam_stotge(f2pysetupfunc)
      use ensdam_stotge, only : ran_te
      interface 
      subroutine f2pywrap_ensdam_stotge_ranv_tg (tgvsmpl, matarm, vecbm,&
     & f2py_tgvsmpl_d0, f2py_tgvsmpl_d1, f2py_matarm_d1)
      integer f2py_tgvsmpl_d0
      integer f2py_tgvsmpl_d1
      integer f2py_matarm_d1
      real(kind=8) tgvsmpl(f2py_tgvsmpl_d0,f2py_tgvsmpl_d1)
      real(kind=8) matarm(size(tgvsmpl,2),f2py_matarm_d1)
      real(kind=8) vecbm(size(matarm,2))
      end subroutine f2pywrap_ensdam_stotge_ranv_tg 
      subroutine f2pywrap_ensdam_stotge_ran_tg (tgsmpl, aa, bb, f2py_tgs&
     &mpl_d0)
      real(kind=8) aa
      real(kind=8) bb
      integer f2py_tgsmpl_d0
      real(kind=8) tgsmpl(f2py_tgsmpl_d0)
      end subroutine f2pywrap_ensdam_stotge_ran_tg
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_ensdam_stotge_ranv_tg,f2pywrap_ensdam_&
     &stotge_ran_tg,ran_te)
      end subroutine f2pyinitensdam_stotge

      subroutine f2pywrap_ensdam_stoutil_cdf_gaussian (cdf_gaussianf2pyw&
     &rap, x)
      use ensdam_stoutil, only : cdf_gaussian
      real(kind=8) x
      real(kind=8) cdf_gaussianf2pywrap
      cdf_gaussianf2pywrap = cdf_gaussian(x)
      end subroutine f2pywrap_ensdam_stoutil_cdf_gaussian
      subroutine f2pywrap_ensdam_stoutil_pdf_gaussian (pdf_gaussianf2pyw&
     &rap, x)
      use ensdam_stoutil, only : pdf_gaussian
      real(kind=8) x
      real(kind=8) pdf_gaussianf2pywrap
      pdf_gaussianf2pywrap = pdf_gaussian(x)
      end subroutine f2pywrap_ensdam_stoutil_pdf_gaussian
      subroutine f2pywrap_ensdam_stoutil_logpdf_gaussian (logpdf_gaussia&
     &nf2pywrap, x)
      use ensdam_stoutil, only : logpdf_gaussian
      real(kind=8) x
      real(kind=8) logpdf_gaussianf2pywrap
      logpdf_gaussianf2pywrap = logpdf_gaussian(x)
      end subroutine f2pywrap_ensdam_stoutil_logpdf_gaussian
      subroutine f2pywrap_ensdam_stoutil_invcdf_gaussian (invcdf_gaussia&
     &nf2pywrap, rank_bn)
      use ensdam_stoutil, only : invcdf_gaussian
      real(kind=8) rank_bn
      real(kind=8) invcdf_gaussianf2pywrap
      invcdf_gaussianf2pywrap = invcdf_gaussian(rank_bn)
      end subroutine f2pywrap_ensdam_stoutil_invcdf_gaussian
      subroutine f2pywrap_ensdam_stoutil_cdf_gamma (cdf_gammaf2pywrap, a&
     &, x)
      use ensdam_stoutil, only : cdf_gamma
      real(kind=8) a
      real(kind=8) x
      real(kind=8) cdf_gammaf2pywrap
      cdf_gammaf2pywrap = cdf_gamma(a, x)
      end subroutine f2pywrap_ensdam_stoutil_cdf_gamma
      subroutine f2pywrap_ensdam_stoutil_pdf_gamma (pdf_gammaf2pywrap, a&
     &, x)
      use ensdam_stoutil, only : pdf_gamma
      real(kind=8) a
      real(kind=8) x
      real(kind=8) pdf_gammaf2pywrap
      pdf_gammaf2pywrap = pdf_gamma(a, x)
      end subroutine f2pywrap_ensdam_stoutil_pdf_gamma
      subroutine f2pywrap_ensdam_stoutil_logpdf_gamma (logpdf_gammaf2pyw&
     &rap, k, theta, x)
      use ensdam_stoutil, only : logpdf_gamma
      real(kind=8) k
      real(kind=8) theta
      real(kind=8) x
      real(kind=8) logpdf_gammaf2pywrap
      logpdf_gammaf2pywrap = logpdf_gamma(k, theta, x)
      end subroutine f2pywrap_ensdam_stoutil_logpdf_gamma
      subroutine f2pywrap_ensdam_stoutil_invcdf_gamma (invcdf_gammaf2pyw&
     &rap, a, rank_bn)
      use ensdam_stoutil, only : invcdf_gamma
      real(kind=8) a
      real(kind=8) rank_bn
      real(kind=8) invcdf_gammaf2pywrap
      invcdf_gammaf2pywrap = invcdf_gamma(a, rank_bn)
      end subroutine f2pywrap_ensdam_stoutil_invcdf_gamma
      subroutine f2pywrap_ensdam_stoutil_cdf_beta (cdf_betaf2pywrap, a, &
     &b, x)
      use ensdam_stoutil, only : cdf_beta
      real(kind=8) a
      real(kind=8) b
      real(kind=8) x
      real(kind=8) cdf_betaf2pywrap
      cdf_betaf2pywrap = cdf_beta(a, b, x)
      end subroutine f2pywrap_ensdam_stoutil_cdf_beta
      subroutine f2pywrap_ensdam_stoutil_pdf_beta (pdf_betaf2pywrap, a, &
     &b, x)
      use ensdam_stoutil, only : pdf_beta
      real(kind=8) a
      real(kind=8) b
      real(kind=8) x
      real(kind=8) pdf_betaf2pywrap
      pdf_betaf2pywrap = pdf_beta(a, b, x)
      end subroutine f2pywrap_ensdam_stoutil_pdf_beta
      subroutine f2pywrap_ensdam_stoutil_logpdf_beta (logpdf_betaf2pywra&
     &p, a, b, x)
      use ensdam_stoutil, only : logpdf_beta
      real(kind=8) a
      real(kind=8) b
      real(kind=8) x
      real(kind=8) logpdf_betaf2pywrap
      logpdf_betaf2pywrap = logpdf_beta(a, b, x)
      end subroutine f2pywrap_ensdam_stoutil_logpdf_beta
      subroutine f2pywrap_ensdam_stoutil_invcdf_beta (invcdf_betaf2pywra&
     &p, a, b, rank_bn)
      use ensdam_stoutil, only : invcdf_beta
      real(kind=8) a
      real(kind=8) b
      real(kind=8) rank_bn
      real(kind=8) invcdf_betaf2pywrap
      invcdf_betaf2pywrap = invcdf_beta(a, b, rank_bn)
      end subroutine f2pywrap_ensdam_stoutil_invcdf_beta
      
      subroutine f2pyinitensdam_stoutil(f2pysetupfunc)
      use ensdam_stoutil, only : maxiter
      use ensdam_stoutil, only : nominal_accuracy
      use ensdam_stoutil, only : accuracy
      interface 
      subroutine f2pywrap_ensdam_stoutil_cdf_gaussian (cdf_gaussianf2pyw&
     &rap, cdf_gaussian, x)
      real(kind=8) cdf_gaussian
      real(kind=8) x
      real(kind=8) cdf_gaussianf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_cdf_gaussian 
      subroutine f2pywrap_ensdam_stoutil_pdf_gaussian (pdf_gaussianf2pyw&
     &rap, pdf_gaussian, x)
      real(kind=8) pdf_gaussian
      real(kind=8) x
      real(kind=8) pdf_gaussianf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_pdf_gaussian 
      subroutine f2pywrap_ensdam_stoutil_logpdf_gaussian (logpdf_gaussia&
     &nf2pywrap, logpdf_gaussian, x)
      real(kind=8) logpdf_gaussian
      real(kind=8) x
      real(kind=8) logpdf_gaussianf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_logpdf_gaussian 
      subroutine f2pywrap_ensdam_stoutil_invcdf_gaussian (invcdf_gaussia&
     &nf2pywrap, invcdf_gaussian, rank_bn)
      real(kind=8) invcdf_gaussian
      real(kind=8) rank_bn
      real(kind=8) invcdf_gaussianf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_invcdf_gaussian 
      subroutine f2pywrap_ensdam_stoutil_cdf_gamma (cdf_gammaf2pywrap, c&
     &df_gamma, a, x)
      real(kind=8) cdf_gamma
      real(kind=8) a
      real(kind=8) x
      real(kind=8) cdf_gammaf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_cdf_gamma 
      subroutine f2pywrap_ensdam_stoutil_pdf_gamma (pdf_gammaf2pywrap, p&
     &df_gamma, a, x)
      real(kind=8) pdf_gamma
      real(kind=8) a
      real(kind=8) x
      real(kind=8) pdf_gammaf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_pdf_gamma 
      subroutine f2pywrap_ensdam_stoutil_logpdf_gamma (logpdf_gammaf2pyw&
     &rap, logpdf_gamma, k, theta, x)
      real(kind=8) logpdf_gamma
      real(kind=8) k
      real(kind=8) theta
      real(kind=8) x
      real(kind=8) logpdf_gammaf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_logpdf_gamma 
      subroutine f2pywrap_ensdam_stoutil_invcdf_gamma (invcdf_gammaf2pyw&
     &rap, invcdf_gamma, a, rank_bn)
      real(kind=8) invcdf_gamma
      real(kind=8) a
      real(kind=8) rank_bn
      real(kind=8) invcdf_gammaf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_invcdf_gamma 
      subroutine f2pywrap_ensdam_stoutil_cdf_beta (cdf_betaf2pywrap, cdf&
     &_beta, a, b, x)
      real(kind=8) cdf_beta
      real(kind=8) a
      real(kind=8) b
      real(kind=8) x
      real(kind=8) cdf_betaf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_cdf_beta 
      subroutine f2pywrap_ensdam_stoutil_pdf_beta (pdf_betaf2pywrap, pdf&
     &_beta, a, b, x)
      real(kind=8) pdf_beta
      real(kind=8) a
      real(kind=8) b
      real(kind=8) x
      real(kind=8) pdf_betaf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_pdf_beta 
      subroutine f2pywrap_ensdam_stoutil_logpdf_beta (logpdf_betaf2pywra&
     &p, logpdf_beta, a, b, x)
      real(kind=8) logpdf_beta
      real(kind=8) a
      real(kind=8) b
      real(kind=8) x
      real(kind=8) logpdf_betaf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_logpdf_beta 
      subroutine f2pywrap_ensdam_stoutil_invcdf_beta (invcdf_betaf2pywra&
     &p, invcdf_beta, a, b, rank_bn)
      real(kind=8) invcdf_beta
      real(kind=8) a
      real(kind=8) b
      real(kind=8) rank_bn
      real(kind=8) invcdf_betaf2pywrap
      end subroutine f2pywrap_ensdam_stoutil_invcdf_beta
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(maxiter,nominal_accuracy,accuracy,f2pywrap_ensd&
     &am_stoutil_cdf_gaussian,f2pywrap_ensdam_stoutil_pdf_gaussian,f2pyw&
     &rap_ensdam_stoutil_logpdf_gaussian,f2pywrap_ensdam_stoutil_invcdf_&
     &gaussian,f2pywrap_ensdam_stoutil_cdf_gamma,f2pywrap_ensdam_stoutil&
     &_pdf_gamma,f2pywrap_ensdam_stoutil_logpdf_gamma,f2pywrap_ensdam_st&
     &outil_invcdf_gamma,f2pywrap_ensdam_stoutil_cdf_beta,f2pywrap_ensda&
     &m_stoutil_pdf_beta,f2pywrap_ensdam_stoutil_logpdf_beta,f2pywrap_en&
     &sdam_stoutil_invcdf_beta)
      end subroutine f2pyinitensdam_stoutil


